fruits = ["peach", "mango", "grapes", "coconut", "tangerine"]
print("original List:", fruits)
print("First Fruit:", fruits[0])
print("Last Fruit:", [-1])
fruits.append("pineapple")
print("After Append:", fruits)
fruits.insert(2, "papaya")
print("After Insert:", fruits)
fruits.remove("grapes")
print("After Remove:", fruits)
remove = fruits.pop()
print("Removed Fruit:", remove)
print("After Pop:", fruits)
print("Total Fruits:", len(fruits))
fruits.sort()
print("Sorted List:", fruits)
fruits.reverse()
print("Reversed List:", fruits)
print("Is mango present?" , "mango" in fruits)