file = open("bucket-list,txt", "w")
file.write("Visit Japan\n")
file.write("Learn Python\n")
file.write("Go Skydiving\n")
file.close()
file = open("bucket-list,txt", "r")
content = file.read()
print("Initial Bucket List:")
print(content)
file.close()
file = open("bucket-list,txt", "r")
items = file.readlines()
print("Number of Items:", len(items))
file.close()
file = open("bucket-list,txt", "a")
file.write("Learn Guitar\n")
file.write("Travel Europe\n")
file.close()
file = open("bucket-list,txt", "r")
updated_content = file.read()
print("Updated Bucket List:")
print(updated_content)
file.close()